workflows:
  ionic-capacitor-android-workflow:
    environment:
      groups:
        # - manual_code_signing # <-- (Includes CM_CERTIFICATE, CM_CERTIFICATE_PASSWORD, CM_PROVISIONING_PROFILE)
        # Automatic Code Signing
        # https://appstoreconnect.apple.com/access/api
        - app_store_credentials
    scripts:
      - name: test
        script: echo "$APP_STORE_CONNECT_PRIVATE_KEY"      
          

 
